image: thomasweise/texlive

stages:
  - build

build:
  stage: build
  script:
    - apt-get update -y
    - apt-get install fonts-font-awesome
    - cd examples
    - xelatex resume.tex
  artifacts:
    paths:
      - examples/resume.pdf
